# Generated by Django 5.2 on 2025-08-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("qualification", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="admin_profiles/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("enroll_no", models.CharField(max_length=50)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("computer_science", "Computer Science"),
                            ("electrical_engineering", "Electrical Engineering"),
                            ("mechanical_engineering", "Mechanical Engineering"),
                            ("civil_engineering", "Civil Engineering"),
                            ("imba", "IMBA"),
                            ("imca", "IMCA"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("professional", "Professional"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("11:00-12:00", "11:00 AM - 12:00 PM"),
                            ("12:00-1:00", "12:00 PM - 1:00 PM"),
                            ("1:00-2:00", "1:00 PM - 2:00 PM"),
                            ("2:00-3:00", "2:00 PM - 3:00 PM"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("pending", "Pending")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["-created_at"],
                "unique_together": {("date", "slot")},
            },
        ),
    ]
