# Generated by Django 5.2 on 2025-08-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_remarks"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
    ]
