# Generated by Django 5.2 on 2025-08-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_adminprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.CharField(
                choices=[
                    ("bca", "BCA – General"),
                    ("bsc_applied", "B.Sc – Applied Sciences (Chem/Microbio/Biotech)"),
                    ("bcom_ifma", "B.Com (Int. Finance & Mgmt. Accounting)"),
                    ("bcom", "B.Com – General"),
                    ("bba", "BBA – General"),
                    ("bba_sports", "BBA – Sports Mgmt."),
                    ("bba_event", "BBA – Event Mgmt."),
                    ("be", "B.E – Engineering"),
                    ("llb", "LLB – Law (General)"),
                    ("gnm", "GNM – Nursing & Midwifery"),
                    ("mba", "MBA – General"),
                    ("mca", "MCA – General"),
                    ("msc_it_cyber", "MSc-IT – Cyber Security"),
                    (
                        "msc_applied",
                        "MSc – Applied Sciences (Chem/Microbio/Biotech/MLT)",
                    ),
                    ("m_media_comm", "Media & Communication (Masters)"),
                    ("m_design", "Design (Masters)"),
                    ("m_planning", "Planning (Masters)"),
                    ("mpharm", "M.Pharm – Pharmacy"),
                    ("mpt", "MPT – Physiotherapy"),
                    ("me", "M.E – Engineering"),
                    ("diploma_engineering", "Diploma Engineering"),
                    (
                        "integrated_bachelors",
                        "Integrated Bachelor’s (10th + B.Com/BBA/BCA)",
                    ),
                    ("radio_programming", "Radio Programming"),
                    ("medical_lab_tech", "Medical Lab Technology"),
                    ("vedic_foretelling", "Vedic Foretelling"),
                    ("holistic_early_ed", "Holistic Early Childhood Ed."),
                    ("integrated_mba", "Integrated MBA (BBA → MBA)"),
                    ("integrated_mca", "Integrated MCA (BCA → MCA)"),
                    ("integrated_msc_it", "Integrated MSc-IT (BSc-IT → MSc-IT)"),
                    ("integrated_llb", "Integrated LLB (BBA + LLB)"),
                    (
                        "integrated_mba_entre",
                        "Integrated MBA – Entrepreneurship & Family Business",
                    ),
                    ("b_media_comm", "Media & Communication (Bachelors)"),
                    ("b_design", "Design (Bachelors)"),
                    ("bsc_nursing", "B.Sc – Nursing"),
                    ("bpt", "BPT – Physiotherapy"),
                    ("b_arch", "B.Arch – Architecture"),
                    ("bpharm", "B.Pharm – Pharmacy"),
                    ("phd", "PhD – Doctorate"),
                ],
                max_length=50,
            ),
        ),
    ]
