# Generated by Django 5.2 on 2025-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_appointment_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
